"""kr-vcp-screener: JSON/Markdown 리포트 생성기."""

import json
import os
from datetime import datetime


class VCPReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        report = {
            'skill': 'kr-vcp-screener',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(results),
                'textbook': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Textbook VCP'),
                'strong': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Strong VCP'),
                'good': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Good VCP'),
                'developing': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Developing'),
                'stage2_failed': sum(1 for r in results if not r.get('score_data', {}).get('stage2_passed', True)),
            },
            'results': results,
        }
        filepath = os.path.join(self.output_dir, 'kr_vcp_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        lines = ['# 한국 VCP 패턴 스크리닝 리포트']
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        if results:
            sorted_r = sorted(results, key=lambda x: x.get('score_data', {}).get('total_score', 0), reverse=True)
            lines.append('| # | 종목 | 코드 | 총점 | 등급 | Stage2 | 수축 | Dry-Up | 피봇근접 | RS |')
            lines.append('|:-:|------|:----:|:----:|------|:------:|:----:|:------:|:-------:|:--:|')
            for i, r in enumerate(sorted_r[:20], 1):
                sd = r.get('score_data', {})
                c = sd.get('components', {})
                s2 = 'O' if sd.get('stage2_passed', False) else 'X'
                lines.append(
                    f'| {i} | {r.get("name", "?")} | {r.get("ticker", "?")} '
                    f'| {sd.get("total_score", 0)} | {sd.get("rating", "?")} '
                    f'| {s2} | {c.get("contraction_quality", 0)} '
                    f'| {c.get("volume_pattern", 0)} | {c.get("pivot_proximity", 0)} '
                    f'| {c.get("relative_strength", 0)} |')

        lines.append('\n---\n*Generated by kr-vcp-screener*')
        filepath = os.path.join(self.output_dir, 'kr_vcp_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
