"""kr-pair-trade: JSON/Markdown 리포트 생성기."""

import json
import os
from datetime import datetime


class PairTradeReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        report = {
            'skill': 'kr-pair-trade',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(results),
                'prime': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Prime Pair'),
                'strong': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Strong Pair'),
                'good': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Good Pair'),
                'entry_signals': sum(1 for r in results if r.get('signal', {}).get('signal') == 'ENTRY'),
            },
            'results': results,
        }
        filepath = os.path.join(self.output_dir, 'kr_pair_trade_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        lines = ['# 한국 페어 트레이딩 스크리닝 리포트']
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        if results:
            sorted_r = sorted(results, key=lambda x: x.get('score_data', {}).get('total_score', 0), reverse=True)
            lines.append('| # | 페어 | 총점 | 등급 | 상관 | 공적분 | Z-Score | 시그널 | Half-Life |')
            lines.append('|:-:|------|:----:|------|:----:|:------:|:-------:|--------|:---------:|')
            for i, r in enumerate(sorted_r[:15], 1):
                sd = r.get('score_data', {})
                pair = f'{r.get("ticker_a", "?")} / {r.get("ticker_b", "?")}'
                signal = r.get('signal', {}).get('signal', '?')
                hl = r.get('half_life', '?')
                corr = r.get('correlation', 0)
                coint = 'O' if r.get('is_cointegrated', False) else 'X'
                zs = r.get('zscore', 0)
                lines.append(
                    f'| {i} | {pair} | {sd.get("total_score", 0)} '
                    f'| {sd.get("rating", "?")} | {corr:.2f} '
                    f'| {coint} | {zs:.2f} | {signal} | {hl} |')

        lines.append('\n---\n*Generated by kr-pair-trade*')
        filepath = os.path.join(self.output_dir, 'kr_pair_trade_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
