"""kr-backtest-expert: JSON/Markdown 리포트 생성."""

import json
import os
from datetime import datetime


class BacktestReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, result: dict) -> str:
        report = {
            'skill': 'kr-backtest-expert',
            'generated_at': datetime.now().isoformat(),
            'result': result,
        }
        filepath = os.path.join(self.output_dir,
                                'kr_backtest_eval.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, result: dict) -> str:
        dims = result.get('dimensions', {})
        derived = result.get('derived', {})
        lines = ['# 백테스트 평가 리포트']
        lines.append(f'\n> 판정: **{result.get("verdict", "?")}** '
                     f'({result.get("composite_score", 0)}점/100)')
        lines.append('')
        lines.append('| 차원 | 점수 |')
        lines.append('|------|:----:|')
        for dim, score in dims.items():
            lines.append(f'| {dim} | {score} |')
        lines.append(f'\n- Expectancy: {derived.get("expectancy_pct", 0)}%')
        lines.append(f'- Profit Factor: {derived.get("profit_factor", 0)}')

        flags = result.get('red_flags', [])
        if flags:
            lines.append(f'\n## Red Flags ({len(flags)})')
            for f in flags:
                lines.append(f'- [{f["severity"]}] {f["id"]}')

        lines.append('\n---\n*Generated by kr-backtest-expert*')
        filepath = os.path.join(self.output_dir,
                                'kr_backtest_eval.md')
        with open(filepath, 'w', encoding='utf-8') as f_out:
            f_out.write('\n'.join(lines))
        return filepath
