"""kr-canslim-screener: JSON/Markdown 리포트 생성기."""

import json
import os
from datetime import datetime


class CANSLIMReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        report = {
            'skill': 'kr-canslim-screener',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(results),
                'exceptional_plus': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Exceptional+'),
                'exceptional': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Exceptional'),
                'strong': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Strong'),
                'm_gate_blocked': sum(1 for r in results if r.get('score_data', {}).get('is_m_gate', False)),
            },
            'results': results,
        }
        filepath = os.path.join(self.output_dir, 'kr_canslim_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        lines = ['# 한국 CANSLIM 성장주 스크리닝 리포트']
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        if results:
            sorted_r = sorted(results, key=lambda x: x.get('score_data', {}).get('total_score', 0), reverse=True)
            lines.append('| # | 종목 | 코드 | 총점 | 등급 | C | A | N | S | L | I | M |')
            lines.append('|:-:|------|:----:|:----:|------|:-:|:-:|:-:|:-:|:-:|:-:|:-:|')
            for i, r in enumerate(sorted_r[:20], 1):
                sd = r.get('score_data', {})
                c = sd.get('components', {})
                lines.append(
                    f'| {i} | {r.get("name", "?")} | {r.get("ticker", "?")} '
                    f'| {sd.get("total_score", 0)} | {sd.get("rating", "?")} '
                    f'| {c.get("C", 0)} | {c.get("A", 0)} | {c.get("N", 0)} '
                    f'| {c.get("S", 0)} | {c.get("L", 0)} | {c.get("I", 0)} | {c.get("M", 0)} |')

        lines.append('\n---\n*Generated by kr-canslim-screener*')
        filepath = os.path.join(self.output_dir, 'kr_canslim_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
