"""kr-portfolio-manager: 포트폴리오 분석 리포트 생성."""

from datetime import datetime


class PortfolioReportGenerator:
    """포트폴리오 분석 Markdown 리포트 생성."""

    def generate_analysis_report(self, result: dict) -> str:
        """종합 분석 리포트."""
        if not result.get('valid'):
            return f'# 분석 오류\n\n{result.get("error", "Unknown error")}'

        lines = ['# 포트폴리오 분석 리포트']
        lines.append(f'\n> 분석일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')

        lines.append(f'\n## 포트폴리오 요약')
        lines.append(f'- **총 가치**: {result["total_value"]:,.0f}원')
        lines.append(f'- **종목 수**: {result["position_count"]}')
        lines.append(f'- **현금 비중**: {result["cash_ratio"]:.1%}')

        div = result['diversification']
        lines.append(f'\n## 분산투자 분석')
        lines.append(f'- **상태**: {div["diversification_status"]}')
        lines.append(f'- **최적 범위**: {div["optimal_range"][0]}-{div["optimal_range"][1]}종목')

        if div['concentration_issues']:
            lines.append(f'\n### 집중도 이슈')
            for issue in div['concentration_issues']:
                if issue['type'] == 'position_concentration':
                    lines.append(
                        f'- {issue["name"]} ({issue["symbol"]}): '
                        f'{issue["weight"]:.1%} > {issue["limit"]:.1%}')
                elif issue['type'] == 'sector_concentration':
                    lines.append(
                        f'- {issue["sector"]}: '
                        f'{issue["weight"]:.1%} > {issue["limit"]:.1%}')

        if result.get('large_shareholder_warnings'):
            lines.append(f'\n## ⚠ 대주주 경고')
            for w in result['large_shareholder_warnings']:
                lines.append(
                    f'- {w["name"]} ({w["symbol"]}): '
                    f'{w["value"]:,.0f}원 ≥ {w["threshold"]:,.0f}원 '
                    f'(양도세 {w["tax_rate"]:.0%})')

        alloc = result.get('allocation', {})
        if alloc.get('sector'):
            lines.append(f'\n## 섹터 배분')
            lines.append(f'| 섹터 | 금액 | 비중 |')
            lines.append(f'|------|------|------|')
            for sector, info in sorted(
                alloc['sector'].items(),
                key=lambda x: x[1]['weight'], reverse=True
            ):
                lines.append(
                    f'| {sector} | {info["value"]:,.0f}원 | '
                    f'{info["weight"]:.1%} |')

        if result.get('excess_cash'):
            lines.append(f'\n## 현금 배분 필요')
            lines.append(f'현금 비중이 10%를 초과합니다. 투자 배분을 검토하세요.')

        lines.append(f'\n---\n*Generated by kr-portfolio-manager*')
        return '\n'.join(lines)
