"""장 초반 브리핑 리포트 생성 모듈.

3개 Section(시장데이터 + 일정 + 핫키워드)을 조합하여 마크다운 리포트 생성.
"""

import os
from datetime import datetime
from pathlib import Path

from market_data_collector import CATEGORY_ORDER, format_price, format_change


# 카테고리 한글 표시명
CATEGORY_DISPLAY = {
    '미국지수': '미국지수',
    '환율': '환율',
    '미국국채': '미국국채',
    '유가': '유가',
    '안전자산': '안전자산',
    '광물': '광물',
    '농산물': '농산물',
    '운임지수': '운임지수',
}


def _build_header(execution_time: str = None) -> str:
    """리포트 헤더."""
    if not execution_time:
        execution_time = datetime.now().strftime('%Y-%m-%d %H:%M')
    return (
        f'# 장 초반 브리핑\n'
        f'> 생성일: {execution_time} | 대상: 글로벌 시장 + 국내 증시\n'
        f'> 데이터 소스: yfinance (Tier 1) + WebSearch (Tier 4)\n'
    )


def _build_section1_market(market_data: dict) -> str:
    """Section 1: 글로벌 시장 현황."""
    lines = ['\n## Section 1: 글로벌 시장 현황\n']

    categories = market_data.get('categories', {})
    summary = market_data.get('summary', {})

    lines.append(f'> 수집: {summary.get("success", 0)}/{summary.get("total", 27)}개 항목\n')

    for cat in CATEGORY_ORDER:
        items = categories.get(cat, [])
        if not items:
            continue

        display = CATEGORY_DISPLAY.get(cat, cat)
        lines.append(f'**[{display}]**')
        for item in items:
            price_str = format_price(item.get('price'), item.get('unit', ''))
            change_str = format_change(item.get('change_pct'))
            name = item.get('name', '')
            lines.append(f'{name}: {price_str} {change_str}')
        lines.append('')

    return '\n'.join(lines)


def _build_section2_calendar(events: list, month: int = None) -> str:
    """Section 2: 당월 주요 일정."""
    if month is None:
        month = datetime.now().month

    lines = [f'\n## Section 2: {month}월 주요 일정\n']

    if not events:
        lines.append('- 등록된 일정 없음\n')
        return '\n'.join(lines)

    for e in events:
        day_part = e.get('date', '').split('-')
        if len(day_part) == 3:
            day = day_part[2].lstrip('0') or '0'
            lines.append(f"- {month}/{day} {e['event']}")
        else:
            lines.append(f"- {e['event']}")

    lines.append('')
    return '\n'.join(lines)


def _build_section3_keywords(hot_keywords: dict) -> str:
    """Section 3: 핫 키워드 + 한줄평."""
    lines = ['\n## Section 3: 장초반 핫 키워드\n']

    keywords = hot_keywords.get('keywords', [])
    if not keywords:
        lines.append('핫 키워드 수집 실패 또는 데이터 없음\n')
        return '\n'.join(lines)

    for kw in keywords:
        rank = kw.get('rank', '?')
        headline = kw.get('headline', '')
        lines.append(f'### 핫 키워드 {rank}: {headline}\n')

        summary = kw.get('summary', '')
        if summary:
            lines.append(f'**핵심 요약**: {summary}\n')

        impact = kw.get('impact', '')
        if impact:
            lines.append(f'**시장 영향**: {impact}\n')

        stocks = kw.get('related_stocks', [])
        if stocks:
            lines.append(f'**관련주**: {", ".join(stocks)}\n')

        lines.append('')

    one_liner = hot_keywords.get('one_liner', '')
    if one_liner:
        lines.append(f'## 장초반 한줄평\n')
        lines.append(f'**{one_liner}**\n')

    return '\n'.join(lines)


def _build_footer() -> str:
    """리포트 푸터."""
    return '\n---\n*Generated by kr-morning-briefing*\n'


def generate_report(
    market_data: dict,
    calendar_events: list,
    hot_keywords: dict,
    execution_time: str = None,
) -> dict:
    """3개 Section을 조합하여 마크다운 리포트 생성.

    Returns:
        {md_content, file_path, sections: {market_data, calendar, hot_keywords}}
    """
    month = datetime.now().month

    parts = [_build_header(execution_time)]

    s1_ok = bool(market_data and market_data.get('items'))
    s2_ok = bool(calendar_events)
    s3_ok = bool(hot_keywords and hot_keywords.get('keywords'))

    parts.append(_build_section1_market(market_data or {}))
    parts.append(_build_section2_calendar(calendar_events or [], month))
    parts.append(_build_section3_keywords(hot_keywords or {}))
    parts.append(_build_footer())

    md_content = '\n'.join(parts)
    date_str = datetime.now().strftime('%Y%m%d')
    file_path = f'reports/kr-morning-briefing_market_장초반브리핑_{date_str}.md'

    return {
        'md_content': md_content,
        'file_path': file_path,
        'sections': {
            'market_data': s1_ok,
            'calendar': s2_ok,
            'hot_keywords': s3_ok,
        },
    }


def save_report(md_content: str, date_str: str = None) -> str:
    """리포트를 reports/ 디렉토리에 저장.

    Returns:
        저장된 파일의 절대 경로
    """
    if not date_str:
        date_str = datetime.now().strftime('%Y%m%d')

    reports_dir = os.path.join(os.path.dirname(__file__), '..', '..', '..', 'reports')
    os.makedirs(reports_dir, exist_ok=True)

    filename = f'kr-morning-briefing_market_장초반브리핑_{date_str}.md'
    filepath = os.path.join(reports_dir, filename)

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(md_content)

    return os.path.abspath(filepath)
