"""kr-earnings-trade: JSON/Markdown 리포트 생성기."""

import json
import os
from datetime import datetime


class EarningsTradeReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        report = {
            'skill': 'kr-earnings-trade',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(results),
                'grade_a': sum(1 for r in results if r.get('grade') == 'A'),
                'grade_b': sum(1 for r in results if r.get('grade') == 'B'),
                'grade_c': sum(1 for r in results if r.get('grade') == 'C'),
                'grade_d': sum(1 for r in results if r.get('grade') == 'D'),
            },
            'results': results,
        }
        filepath = os.path.join(self.output_dir, 'kr_earnings_trade_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        lines = ['# 한국 실적 트레이드 분석 리포트']
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        if results:
            sorted_r = sorted(results, key=lambda x: x.get('final_score', 0),
                              reverse=True)
            lines.append('| # | 종목 | 등급 | 점수 | 갭 | 추세 | 거래량 | MA200 | MA50 | 보너스 |')
            lines.append('|:-:|------|:----:|:----:|:---:|:----:|:------:|:-----:|:----:|:------:|')
            for i, r in enumerate(sorted_r[:20], 1):
                ticker = r.get('ticker', '?')
                name = r.get('name', '')
                grade = r.get('grade', '?')
                score = r.get('final_score', 0)
                gap = r.get('gap_pct', 0)
                trend = r.get('trend_pct', 0)
                vol = r.get('volume_ratio', 0)
                ma200 = r.get('ma200_distance', 0)
                ma50 = r.get('ma50_distance', 0)
                bonus = 'O' if r.get('bonus_applied') else '-'
                display = f'{ticker} {name}' if name else ticker
                lines.append(
                    f'| {i} | {display} | {grade} | {score} '
                    f'| {gap:+.1f}% | {trend:+.1f}% | {vol:.1f}x '
                    f'| {ma200:+.1f}% | {ma50:+.1f}% | {bonus} |')

        lines.append('\n---\n*Generated by kr-earnings-trade*')
        filepath = os.path.join(self.output_dir, 'kr_earnings_trade_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
