"""kr-options-advisor: 옵션 분석 리포트 생성."""

from datetime import datetime


class OptionsReportGenerator:
    """옵션 분석 Markdown 리포트 생성."""

    def generate_pricing_report(self, result: dict) -> str:
        """옵션 가격결정 리포트."""
        lines = [f'# KOSPI200 옵션 분석']
        lines.append(f'\n> 분석일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append(f'\n## 기본 정보')
        lines.append(f'| 항목 | 값 |')
        lines.append(f'|------|---|')
        lines.append(f'| KOSPI200 | {result["spot"]} |')
        lines.append(f'| 행사가 | {result["strike"]} |')
        lines.append(f'| 잔존일수 | {result["dte"]}일 |')
        lines.append(f'| 옵션 유형 | {result["option_type"].upper()} |')
        lines.append(f'| 변동성 | {result["volatility"]:.1%} |')
        lines.append(f'| 머니니스 | {result["moneyness"]} |')

        lines.append(f'\n## 이론가')
        lines.append(f'- **가격**: {result["price"]:.4f}pt '
                     f'({result["price_krw"]:,}원)')

        lines.append(f'\n## 그릭스')
        lines.append(f'| Greek | 값 |')
        lines.append(f'|-------|---|')
        for k, v in result['greeks'].items():
            lines.append(f'| {k.capitalize()} | {v} |')

        lines.append(f'\n---\n*Generated by kr-options-advisor*')
        return '\n'.join(lines)

    def generate_strategy_report(self, result: dict) -> str:
        """전략 시뮬레이션 리포트."""
        lines = [f'# KOSPI200 옵션 전략: {result["strategy"]}']
        lines.append(f'\n> 분석일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append(f'> 카테고리: {result["category"]}')

        lines.append(f'\n## 시장 조건')
        lines.append(f'- KOSPI200: {result["spot"]}')
        lines.append(f'- DTE: {result["dte"]}일')
        lines.append(f'- 변동성: {result["volatility"]:.1%}')

        lines.append(f'\n## 레그 구성')
        lines.append(f'| 행동 | 유형 | 행사가 | 프리미엄 | 원화 |')
        lines.append(f'|------|------|--------|----------|------|')
        for leg in result['legs']:
            action = '매수' if leg['action'] == 'buy' else '매도'
            lines.append(
                f'| {action} | {leg["type"].upper()} | '
                f'{leg["strike"]} | {leg["premium"]:.4f}pt | '
                f'{leg["premium_krw"]:,}원 |')

        lines.append(f'\n## 손익 분석')
        cost = result['cost']
        lines.append(
            f'- **순비용**: {cost["net_premium"]:.4f}pt '
            f'({"지불" if cost["is_debit"] else "수취"}) '
            f'{cost["net_premium_krw"]:,}원')
        lines.append(
            f'- **최대이익**: {result["max_profit"]:.4f}pt '
            f'({result["max_profit_krw"]:,}원)')
        lines.append(
            f'- **최대손실**: {result["max_loss"]:.4f}pt '
            f'({result["max_loss_krw"]:,}원)')
        lines.append(f'- **손익비**: {result["risk_reward_ratio"]}')

        if result.get('breakevens'):
            lines.append(
                f'- **손익분기점**: '
                f'{", ".join(str(b) for b in result["breakevens"])}')

        lines.append(f'\n## 합산 그릭스')
        lines.append(f'| Greek | 값 |')
        lines.append(f'|-------|---|')
        for k, v in result['greeks'].items():
            lines.append(f'| {k.capitalize()} | {v} |')

        if result.get('warnings'):
            lines.append(f'\n## ⚠ 경고')
            for w in result['warnings']:
                lines.append(f'- {w}')

        lines.append(f'\n---\n*Generated by kr-options-advisor*')
        return '\n'.join(lines)
