"""
kr-value-dividend: JSON/Markdown 리포트 생성기.
"""

import json
import os
from datetime import datetime


class ValueDividendReportGenerator:
    """배당 가치주 스크리닝 리포트 생성."""

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        """JSON 리포트 생성.

        Args:
            results: [{ticker, name, score_data, filter_data, ...}, ...]
            metadata: {market, timestamp, ...}
        Returns:
            JSON 파일 경로
        """
        report = {
            'skill': 'kr-value-dividend',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total_screened': len(results),
                'excellent': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Excellent'),
                'good': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Good'),
                'average': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Average'),
                'below_average': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Below Average'),
            },
            'results': results,
        }

        filepath = os.path.join(self.output_dir, 'kr_value_dividend_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        """Markdown 리포트 생성.

        Args:
            results: [{ticker, name, score_data, filter_data, ...}, ...]
            metadata: {market, timestamp, ...}
        Returns:
            Markdown 파일 경로
        """
        lines = []
        lines.append('# 한국 배당 가치주 스크리닝 리포트')
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        if metadata:
            lines.append(f'> 시장: {metadata.get("market", "ALL")}')
        lines.append('')

        # 요약
        excellent = [r for r in results if r.get('score_data', {}).get('rating') == 'Excellent']
        good = [r for r in results if r.get('score_data', {}).get('rating') == 'Good']

        lines.append('## 요약')
        lines.append(f'- 스크리닝 통과 종목: **{len(results)}개**')
        lines.append(f'- Excellent: **{len(excellent)}개**')
        lines.append(f'- Good: **{len(good)}개**')
        lines.append('')

        # 상위 종목 테이블
        if results:
            sorted_results = sorted(results,
                                    key=lambda r: r.get('score_data', {}).get('total_score', 0),
                                    reverse=True)

            lines.append('## 상위 종목')
            lines.append('')
            lines.append('| 순위 | 종목 | 코드 | 총점 | 등급 | Value | Growth | Sustain | Quality |')
            lines.append('|:----:|------|:----:|:----:|------|:-----:|:------:|:-------:|:-------:|')

            for i, r in enumerate(sorted_results[:20], 1):
                sd = r.get('score_data', {})
                comps = sd.get('components', {})
                lines.append(
                    f'| {i} | {r.get("name", "?")} | {r.get("ticker", "?")} '
                    f'| {sd.get("total_score", 0)} | {sd.get("rating", "?")} '
                    f'| {comps.get("value", 0)} | {comps.get("growth", 0)} '
                    f'| {comps.get("sustainability", 0)} | {comps.get("quality", 0)} |'
                )

        lines.append('')
        lines.append('---')
        lines.append(f'*Generated by kr-value-dividend*')

        filepath = os.path.join(self.output_dir, 'kr_value_dividend_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
