"""kr-economic-calendar: JSON/Markdown 리포트 생성기."""

import json
import os
from datetime import datetime


IMPACT_LABELS = {
    'H': '🔴 High',
    'M': '🟡 Medium',
    'L': '🟢 Low',
}


class EconomicCalendarReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, events: list, metadata: dict = None) -> str:
        """JSON 리포트 생성.

        Args:
            events: 경제 이벤트 목록
            metadata: 추가 메타데이터

        Returns:
            생성된 파일 경로
        """
        report = {
            'skill': 'kr-economic-calendar',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(events),
                'high_impact': sum(1 for e in events if e.get('impact') == 'H'),
                'medium_impact': sum(1 for e in events if e.get('impact') == 'M'),
                'low_impact': sum(1 for e in events if e.get('impact') == 'L'),
            },
            'events': events,
        }
        filepath = os.path.join(self.output_dir, 'kr_economic_calendar_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, events: list, metadata: dict = None) -> str:
        """Markdown 리포트 생성.

        Args:
            events: 경제 이벤트 목록
            metadata: 추가 메타데이터

        Returns:
            생성된 파일 경로
        """
        lines = ['# 한국 경제 캘린더 리포트']
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        if not events:
            lines.append('조회 기간 내 예정된 경제 이벤트가 없습니다.')
        else:
            # 임팩트별 요약
            high = sum(1 for e in events if e.get('impact') == 'H')
            med = sum(1 for e in events if e.get('impact') == 'M')
            low = sum(1 for e in events if e.get('impact') == 'L')
            lines.append(f'**총 {len(events)}개 이벤트** '
                         f'(High: {high}, Medium: {med}, Low: {low})')
            lines.append('')

            # 테이블
            lines.append('| 날짜 | 임팩트 | 지표명 | 발표 기관 | 주기 |')
            lines.append('|------|:------:|--------|----------|------|')
            for ev in events:
                impact = IMPACT_LABELS.get(ev.get('impact', ''), ev.get('impact', '?'))
                lines.append(
                    f'| {ev.get("date", "?")} '
                    f'| {impact} '
                    f'| {ev.get("name", "?")} '
                    f'| {ev.get("source", "?")} '
                    f'| {ev.get("frequency", "?")} |')

        lines.append('\n---\n*Generated by kr-economic-calendar*')
        filepath = os.path.join(self.output_dir, 'kr_economic_calendar_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
