"""
kr-dividend-pullback: JSON/Markdown 리포트 생성기.
"""

import json
import os
from datetime import datetime


class PullbackReportGenerator:
    """배당 성장 풀백 스크리닝 리포트 생성."""

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        report = {
            'skill': 'kr-dividend-pullback',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total_screened': len(results),
                'strong_buy': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Strong Buy'),
                'buy': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Buy'),
                'watch': sum(1 for r in results if r.get('score_data', {}).get('rating') == 'Watch'),
            },
            'results': results,
        }

        filepath = os.path.join(self.output_dir, 'kr_dividend_pullback_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        lines = []
        lines.append('# 한국 배당 성장 풀백 스크리닝 리포트')
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        strong_buy = [r for r in results if r.get('score_data', {}).get('rating') == 'Strong Buy']
        buy = [r for r in results if r.get('score_data', {}).get('rating') == 'Buy']

        lines.append('## 요약')
        lines.append(f'- 스크리닝 통과 종목: **{len(results)}개**')
        lines.append(f'- Strong Buy: **{len(strong_buy)}개**')
        lines.append(f'- Buy: **{len(buy)}개**')
        lines.append('')

        if results:
            sorted_results = sorted(results,
                                    key=lambda r: r.get('score_data', {}).get('total_score', 0),
                                    reverse=True)

            lines.append('## 상위 종목')
            lines.append('')
            lines.append('| 순위 | 종목 | 코드 | 총점 | 등급 | RSI | CAGR | DivGrowth | FinQual | TechSetup | Val |')
            lines.append('|:----:|------|:----:|:----:|------|:---:|:----:|:---------:|:-------:|:---------:|:---:|')

            for i, r in enumerate(sorted_results[:15], 1):
                sd = r.get('score_data', {})
                comps = sd.get('components', {})
                lines.append(
                    f'| {i} | {r.get("name", "?")} | {r.get("ticker", "?")} '
                    f'| {sd.get("total_score", 0)} | {sd.get("rating", "?")} '
                    f'| {r.get("rsi", 0):.1f} | {r.get("cagr", 0):.1f}% '
                    f'| {comps.get("dividend_growth", 0)} | {comps.get("financial_quality", 0)} '
                    f'| {comps.get("technical_setup", 0)} | {comps.get("valuation", 0)} |'
                )

        lines.append('')
        lines.append('---')
        lines.append(f'*Generated by kr-dividend-pullback*')

        filepath = os.path.join(self.output_dir, 'kr_dividend_pullback_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
