"""시장폭 분석 리포트 생성 (JSON + Markdown)."""

import os
import json
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class ReportGenerator:
    """JSON + Markdown 리포트 생성."""

    def __init__(self, output_dir: str = 'reports/'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate(self, breadth_data: dict, score_data: dict,
                 trend: str = 'insufficient') -> dict:
        """JSON + Markdown 리포트 생성.

        Returns:
            {'json_path': str, 'md_path': str}
        """
        timestamp = datetime.now().strftime('%Y-%m-%d_%H%M%S')
        market = breadth_data.get('market', 'UNKNOWN')

        # JSON 리포트
        json_data = {
            'timestamp': timestamp,
            'market': market,
            'breadth': breadth_data,
            'score': score_data,
            'trend': trend,
        }
        json_path = os.path.join(self.output_dir, f'kr_breadth_{market}_{timestamp}.json')
        with open(json_path, 'w', encoding='utf-8') as f:
            json.dump(json_data, f, ensure_ascii=False, indent=2, default=str)

        # Markdown 리포트
        md_content = self._generate_markdown(breadth_data, score_data, trend)
        md_path = os.path.join(self.output_dir, f'kr_breadth_{market}_{timestamp}.md')
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(md_content)

        logger.info(f"리포트 저장: {json_path}, {md_path}")
        return {'json_path': json_path, 'md_path': md_path}

    def _generate_markdown(self, breadth_data: dict, score_data: dict,
                           trend: str) -> str:
        """Markdown 리포트 내용 생성."""
        market = breadth_data.get('market', '')
        date = breadth_data.get('date', '')
        raw = breadth_data.get('breadth_raw', 0)
        ma8 = breadth_data.get('breadth_8ma', 0)
        ma200 = breadth_data.get('breadth_200ma', 0)
        total = breadth_data.get('total_stocks', 0)
        above = breadth_data.get('above_200ma', 0)
        index_price = breadth_data.get('index_price', 0)

        composite = score_data.get('composite_score', 0)
        zone = score_data.get('health_zone', '')
        zone_kr = score_data.get('health_zone_kr', '')
        exposure = score_data.get('equity_exposure', '')
        components = score_data.get('components', {})
        strongest = score_data.get('strongest_component', '')
        weakest = score_data.get('weakest_component', '')

        trend_kr = {
            'improving': '개선중 ↑',
            'deteriorating': '악화중 ↓',
            'stable': '안정 →',
            'insufficient': '데이터 축적중',
        }.get(trend, trend)

        lines = []
        lines.append(f"# 한국 시장폭 분석 리포트 - {market}")
        lines.append(f"")
        lines.append(f"> 날짜: {date}")
        lines.append(f"> 대상: {market} ({total}종목)")
        lines.append(f"> 지수: {index_price:,.0f}")
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")
        lines.append(f"## 종합 점수: {composite}/100 ({zone} - {zone_kr})")
        lines.append(f"## 권장 주식 비중: {exposure}")
        lines.append(f"## 점수 추세: {trend_kr}")
        lines.append(f"")
        lines.append(f"---")
        lines.append(f"")

        # 컴포넌트 상세
        lines.append(f"## 컴포넌트 상세")
        lines.append(f"")
        lines.append(f"| 컴포넌트 | 점수 | 가중치 | 가중점수 | 판정 |")
        lines.append(f"|----------|:----:|:-----:|:-------:|------|")
        for key, data in components.items():
            name = {
                'breadth_level': 'Breadth Level & Trend',
                'crossover': '8MA vs 200MA Crossover',
                'cycle': 'Peak/Trough Cycle',
                'bearish': 'Bearish Signal',
                'percentile': 'Historical Percentile',
                'divergence': 'Index Divergence',
            }.get(key, key)
            score = data.get('score', 0)
            weight = data.get('weight', 0)
            weighted = data.get('weighted', 0)
            detail = data.get('detail', '')
            lines.append(f"| {name} | {score} | {weight*100:.0f}% | {weighted:.1f} | {detail} |")

        lines.append(f"")
        lines.append(f"- **최강 컴포넌트**: {strongest}")
        lines.append(f"- **최약 컴포넌트**: {weakest}")
        lines.append(f"")

        # 시장폭 현황
        lines.append(f"## 시장폭 현황")
        lines.append(f"")
        lines.append(f"- {market} 중 200MA 위: **{above}개** ({raw:.1f}%)")
        lines.append(f"- 8일 평균: {ma8:.1f}%")
        lines.append(f"- 200일 평균: {ma200:.1f}%")
        lines.append(f"- 추세: {breadth_data.get('trend', 'flat')}")
        if breadth_data.get('bearish_signal'):
            lines.append(f"- **약세 신호 활성**")
        lines.append(f"")

        lines.append(f"---")
        lines.append(f"")
        lines.append(f"*Generated by kr-market-breadth skill*")

        return '\n'.join(lines)
