"""kr-institutional-flow: JSON/Markdown 리포트 생성기."""

import json
import os
from datetime import datetime


class InstitutionalFlowReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        report = {
            'skill': 'kr-institutional-flow',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(results),
                'strong_accumulation': sum(
                    1 for r in results
                    if r.get('rating') == 'Strong Accumulation'),
                'accumulation': sum(
                    1 for r in results
                    if r.get('rating') == 'Accumulation'),
                'distribution': sum(
                    1 for r in results
                    if r.get('rating') == 'Distribution'),
            },
            'results': results,
        }
        filepath = os.path.join(self.output_dir,
                                'kr_institutional_flow_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        lines = ['# 한국 수급 동향 분석 리포트']
        lines.append(
            f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        if results:
            sorted_r = sorted(results,
                              key=lambda x: x.get('final_score', 0),
                              reverse=True)
            lines.append(
                '| # | 종목 | 등급 | 점수 | 외국인 | 기관 '
                '| 일관성 | 거래량 | 보너스 |')
            lines.append(
                '|:-:|------|:----:|:----:|:------:|:----:'
                '|:------:|:------:|:------:|')
            for i, r in enumerate(sorted_r[:20], 1):
                ticker = r.get('ticker', '?')
                name = r.get('name', '')
                rating = r.get('rating', '?')
                score = r.get('final_score', 0)
                foreign = r.get('foreign_signal', '?')
                inst = r.get('inst_signal', '?')
                consistency = r.get('consistency_ratio', 0)
                vol_ratio = r.get('volume_ratio', 0)
                bonus = 'O' if r.get('bonus_applied') else '-'
                display = f'{ticker} {name}' if name else ticker
                lines.append(
                    f'| {i} | {display} | {rating} | {score} '
                    f'| {foreign} | {inst} | {consistency:.0f}% '
                    f'| {vol_ratio:.1f}x | {bonus} |')

        lines.append('\n---\n*Generated by kr-institutional-flow*')
        filepath = os.path.join(self.output_dir,
                                'kr_institutional_flow_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
