"""
kr-pead-screener: JSON/Markdown 리포트 생성기.
"""

import json
import os
from datetime import datetime


class PEADReportGenerator:
    """PEAD 스크리닝 리포트 생성."""

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, results: list, metadata: dict = None) -> str:
        report = {
            'skill': 'kr-pead-screener',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(results),
                'by_stage': {
                    'MONITORING': sum(1 for r in results if r.get('stage') == 'MONITORING'),
                    'SIGNAL_READY': sum(1 for r in results if r.get('stage') == 'SIGNAL_READY'),
                    'BREAKOUT': sum(1 for r in results if r.get('stage') == 'BREAKOUT'),
                    'EXPIRED': sum(1 for r in results if r.get('stage') == 'EXPIRED'),
                },
            },
            'results': results,
        }

        filepath = os.path.join(self.output_dir, 'kr_pead_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, results: list, metadata: dict = None) -> str:
        lines = []
        lines.append('# 한국 PEAD 스크리닝 리포트')
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        active = [r for r in results if r.get('stage') not in ('EXPIRED', None)]
        breakouts = [r for r in results if r.get('stage') == 'BREAKOUT']

        lines.append('## 요약')
        lines.append(f'- 활성 종목: **{len(active)}개**')
        lines.append(f'- BREAKOUT: **{len(breakouts)}개**')
        lines.append('')

        if results:
            lines.append('## 종목 현황')
            lines.append('')
            lines.append('| 종목 | 코드 | 스테이지 | 갭(%) | 총점 | 등급 |')
            lines.append('|------|:----:|---------|:-----:|:----:|------|')

            for r in sorted(results, key=lambda x: x.get('score_data', {}).get('total_score', 0), reverse=True):
                sd = r.get('score_data', {})
                lines.append(
                    f'| {r.get("name", "?")} | {r.get("ticker", "?")} '
                    f'| {r.get("stage", "?")} | {r.get("gap_pct", 0):.1f} '
                    f'| {sd.get("total_score", 0)} | {sd.get("rating", "?")} |'
                )

        lines.append('')
        lines.append('---')
        lines.append(f'*Generated by kr-pead-screener*')

        filepath = os.path.join(self.output_dir, 'kr_pead_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
