"""kr-earnings-calendar: JSON/Markdown 리포트 생성기."""

import json
import os
from datetime import datetime


class EarningsCalendarReportGenerator:

    def __init__(self, output_dir: str = './output'):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def generate_json(self, disclosures: list, metadata: dict = None) -> str:
        """JSON 리포트 생성."""
        confirmed = [d for d in disclosures if d.get('is_confirmed')]
        preliminary = [d for d in disclosures if d.get('is_preliminary')]

        report = {
            'skill': 'kr-earnings-calendar',
            'generated_at': datetime.now().isoformat(),
            'metadata': metadata or {},
            'summary': {
                'total': len(disclosures),
                'confirmed': len(confirmed),
                'preliminary': len(preliminary),
            },
            'disclosures': disclosures,
        }
        filepath = os.path.join(self.output_dir, 'kr_earnings_calendar_report.json')
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        return filepath

    def generate_markdown(self, disclosures: list, metadata: dict = None) -> str:
        """Markdown 리포트 생성."""
        lines = ['# 한국 실적 캘린더 리포트']
        lines.append(f'\n> 생성일시: {datetime.now().strftime("%Y-%m-%d %H:%M")}')
        lines.append('')

        if not disclosures:
            lines.append('조회 기간 내 실적 관련 공시가 없습니다.')
        else:
            confirmed = [d for d in disclosures if d.get('is_confirmed')]
            preliminary = [d for d in disclosures if d.get('is_preliminary')]

            lines.append(f'**총 {len(disclosures)}건** '
                         f'(확정: {len(confirmed)}, 잠정: {len(preliminary)})')
            lines.append('')

            # 일자별 그룹핑
            by_date = {}
            for d in sorted(disclosures, key=lambda x: x.get('date', '')):
                date = d.get('date', 'Unknown')
                by_date.setdefault(date, []).append(d)

            for date, items in by_date.items():
                lines.append(f'### {date}')
                lines.append('')
                lines.append('| 종목 | 유형 | 시간 | 시총(억) |')
                lines.append('|------|------|:----:|:-------:|')
                for item in sorted(items, key=lambda x: x.get('market_cap', 0),
                                   reverse=True):
                    name = item.get('name', item.get('ticker', '?'))
                    rtype = item.get('report_type', '?')
                    timing = item.get('timing', '?')
                    mcap = item.get('market_cap', 0)
                    mcap_eok = round(mcap / 100_000_000) if mcap else '?'
                    lines.append(f'| {name} | {rtype} | {timing} | {mcap_eok} |')
                lines.append('')

        lines.append('---\n*Generated by kr-earnings-calendar*')
        filepath = os.path.join(self.output_dir, 'kr_earnings_calendar_report.md')
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        return filepath
